/* 21 */
SELECT MIN(CUS_BALANCE) AS 'Minimum Balance', 
MAX(CUS_BALANCE) AS 'Maximum Balance', 
ROUND(AVG(CUS_BALANCE),2) AS 'Average Balance' 
FROM CUSTOMER 
WHERE CUS_CODE IN (SELECT CUS_CODE FROM INVOICE);