# Generated by Django 5.2.6 on 2025-10-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_program', '0002_deliveryaddress_sponsorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver_program.sponsorprofile'),
        ),
    ]
