# Generated by Django 5.2.6 on 2025-11-29 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_program', '0003_profile_sponsor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverWallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_balance', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_wallets',
                'unique_together': {('driver',)},
            },
        ),
        migrations.CreateModel(
            name='SponsorDriverRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('relationship_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('terminated', 'Terminated'), ('completed', 'Completed')], default='active', max_length=20)),
                ('relationship_start_date', models.DateTimeField(auto_now_add=True)),
                ('relationship_end_date', models.DateTimeField(blank=True, null=True)),
                ('driver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_relationships', to=settings.AUTH_USER_MODEL)),
                ('sponsor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sponsor_driver_relationships',
            },
        ),
        migrations.CreateModel(
            name='WalletTransactionHistory',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('adjustment', 'Adjustment'), ('refund', 'Refund'), ('purchase', 'Purchase'), ('reward', 'Reward'), ('penalty', 'Penalty')], max_length=20)),
                ('points_amount', models.IntegerField()),
                ('points_before', models.IntegerField()),
                ('points_after', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_type', models.CharField(blank=True, choices=[('order', 'Order'), ('sponsor_reward', 'Sponsor Reward'), ('admin_adjustment', 'Admin Adjustment'), ('point_conversion', 'Point Conversion'), ('refund', 'Refund'), ('penalty', 'Penalty'), ('bonus', 'Bonus'), ('other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_transactions', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='driver_program.driverwallet')),
            ],
            options={
                'db_table': 'wallet_transaction_history',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
