# Generated by Django 5.2.6 on 2025-11-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_program', '0004_profile_avatar_address_driverwallet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorDriverRelationship',
        ),
    ]
